version: "3.9"
#
# Services definitions
#
services:
    postgres:
        image: postgres:14-alpine
        ports:
            - 5433:5432
        volumes:
            - ./mount/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=har


